### ISSUE TITLE
Remove background in graph

### ISSUE THREAD

**Issue by mehak25** [de-data-lab/voucher-eligibility#110]

**Comment by nsunami** [comment]
I wasn't sure what this issue was referring to---could you put a description?

**Comment by mehak25** [comment]
There we are grid lines in bar plot which I removed.

**Comment by nsunami** [comment]
Got it! I think I found a [code](https://github.com/de-data-lab/voucher-eligibility/pull/117/files#r814900373) that I think addresses this issue. Closing this for now.
