### ISSUE TITLE
Remove axis labeling from the plots whenever the title makes it obvious

### ISSUE THREAD

**Issue by nsunami** [de-data-lab/voucher-eligibility#142]
We want to consider removing axis labels when the title of the plot already implies the labels.

For example, in the below plot we can remove the x-axis (Number of families) if we change the title to "Number of families..."

![image](https://user-images.githubusercontent.com/17035406/156210149-fa7d88ee-7238-4ae8-a597-1abc84404886.png)

**Comment by mehak25** [comment]
#186
