### ISSUE TITLE
Implement logical ordering for counties in bar graphs

### ISSUE THREAD

**Issue by rharrington31** [de-data-lab/voucher-eligibility#56]
Currently counties are ordered alphabetically on the county view:

![image](https://user-images.githubusercontent.com/16887262/153080720-e48a7c16-86e8-4d41-83b6-6b4adb5aa72d.png)

![image](https://user-images.githubusercontent.com/16887262/153081060-1e05cc81-0f0a-4c13-abf9-356ac37b3aa9.png)

This is not an intuitive order, though.

Recommendations:
* Order from North to South to match how people scan the state (from top to bottom: New Castle, Kent, Sussex)
* Order based upon the data, so that the highest percentage is first, etc.

I'd recommend ordering based upon North to South, though.

**Comment by nsunami** [comment]
I agree that the best way is to order from North to South so that the reader will not lose orientation when going from one plot to the next. Fix coming soon.

**Comment by nsunami** [comment]
Fixed via #64
