### ISSUE TITLE
Shorten the heading of the advocates table

### ISSUE THREAD

**Issue by nsunami** [de-data-lab/voucher-eligibility#61]
I think we can shorten the heading of the advocates table:

![image](https://user-images.githubusercontent.com/17035406/153236493-2f799639-6468-4f03-80cd-43f90492c680.png)

Right now the headings are:
- `# Households receiving assisstance`
- `#Households spending above 30% of income on rent`
-  `# Households spending above 50% of income on rent`

We can instead say something like:
- `Receiving Voucher`
- `Spending 30%+ Income on Rent`
- `Spending 50%+ Income on Rent`

I'm also a bit worried about escaping special characters like `#`, `%`, and `+`, especially when downloading to a CSV file.

**Comment by mehak25** [comment]
Resolved in PR #63
