### ISSUE TITLE
Remove decimals from count values in the advocates table

### ISSUE THREAD

**Issue by nsunami** [de-data-lab/voucher-eligibility#62]
The values in the advocates table are showing decimals (e.g., `10.00`). But these numbers are counts, so they could be misleading for users.

![image](https://user-images.githubusercontent.com/17035406/153237354-54e6a2b7-ada3-43b3-9d03-82762ab46d3c.png)

We can hide the decimals there (so that we show integers).

**Comment by mehak25** [comment]
Resolved in PR #63
